version: "2.17"
services:
  cockpit:
    image: stalkcd/cockpit
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    links:
      - extended
      - characteristics
    restart: always
  extended:
    image: stalkcd/extended
    build:
      context: ../stalkcd_extended
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    restart: always
  characteristics:
    image: stalkcd/characteristics
    build:
      context: ../stalkcd_characteristics
      dockerfile: Dockerfile
    volumes:
      - data:/files
    ports:
      - "8082:8082"
    environment:
      - DATABASE_HOST=db
    links:
      - mongodb:db
    restart: always
  mongodb:
    container_name: mongodb
    image: mongodb/mongodb-community-server
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - DATABASE_HOST=db
    ports:
      - "27017:27017"
    restart: always
volumes:
  data:
