version: "3"
services:
  cockpit:
    image: stalkcd/cockpit
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    links:
      - extended
      - characteristics
    restart: always
  extended:
    image: stalkcd/extended
    build:
      context: ../stalkcd_extended
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    restart: always
  characteristics:
    image: stalkcd/characteristics
    build:
      context: ../stalkcd_characteristics
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - DATABASE_HOST=db
      - DB_KEY= "${DB_KEY}"
    restart: always