version: "2.19"
services:
  cockpit:
    image: stalkcd/cockpit
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "8080:80"
  extended:
    image: stalkcd/extended
    build:
      context: ../stalkcd_extended
      dockerfile: Dockerfile
    ports:
    - "8081:8081"
  characteristics:
    image: stalkcd/characteristics
    build:
      context: ../stalkcd_characteristics
      dockerfile: Dockerfile
    volumes:
      - data:/files
    ports:
    - "8082:8082"
    environment:
      - DATABASE_HOST=db
    links:
      - mongodb:db
  mongodb:
    container_name: mongodb
    image: arm64v8/mongo:latest
    platform: linux/arm64/v8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - DATABASE_HOST=db
    ports:
      - "27017:27017"
volumes:
  data: