version: "2.19"
services:
  cockpit:
    image: stalkcd_cockpit
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "8080:80"
  extended:
    image: stalkcd_extended
    build:
      context: ../stalkcd_extended
      dockerfile: Dockerfile.dev
    ports:
    - "8081:8081"
  characteristics:
    image: stalkcd_characteristics
    build:
      context: ../stalkcd_characteristics
      dockerfile: Dockerfile.dev
    volumes:
      - data:/files
    ports:
    - "8082:8082"
    environment:
      - DATABASE_HOST=db
    links:
      - mongodb:db
  mongodb:
    container_name: mongodb
    image: mongodb/mongodb-community-server
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - DATABASE_HOST=db
    ports:
      - "27017:27017"

volumes:
  data:
